run:
  tests: false
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - unused
    - staticcheck
    - gosimple
    - goconst
    - gofumpt
    - revive
  disable:
    - funlen
    - cyclop

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
